input_folder: "data/raw/example"
output_final: "data/processed/example/final_data.csv"

rename_columns:
  - "Date"
  - "Details"
  - "Amount"
  - "Account"

rules_file: "data/reference/categories_example.json"

category_columns: "Details"
amount_column : "Amount"
date_column: "Date"

merge_col: [
  'Date', 
  'Details', 
  'Amount', 
  'Account', 
  'Currency', 
  'Debit/Credit', 
  'Month', 
  'Year'
  ]

encoding: "ISO-8859-15"
skiprows: 6
separator: ";"
file_extensions:
  - ".csv"
